spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_ID}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/pos?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate
